# version: "4"
# services:
#   web:
#     image: mysql
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: admin
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./mysql:/var/lib/mysql
#       - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
services:
  mysql:
    image: mysql:8.4
    container_name: mysql_lfp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lfp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: spring-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lfp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  mysql_data:
